<?php

/**
 * @file
 * This module allows to use different themes than the site default on content
 * creating, editing, and viewing pages.
 */


/**
 * Implements hook_permission().
 */
function content_theme_permission() {

  $perm = array();
  foreach (node_type_get_types() as $type => $value) {
    $info = node_type_get_type($type);

    $perm["select $type content editing theme"] = array(
      'title' => t('%type_name: Select content editing theme', array('%type_name' => $info->name)),
    );
    $perm["select $type content viewing theme"] = array(
      'title' => t('%type_name: Select content viewing theme', array('%type_name' => $info->name)),
    );
  }

  return $perm;
}


/**
 * Implements hook_menu().
 */
function content_theme_menu() {

  $items['admin/appearance/content-theme'] = array(
    'title' => 'Content theme',
    'description' => 'Configure which theme is used when content is created, edited or be viewed.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('content_theme_admin_content_wide'),
    'access arguments' => array('administer themes'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 40,
    'file' => 'content_theme.admin.inc',
  );
  $items['admin/appearance/content-theme/content-wide'] = array(
    'title' => 'Content wide',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/appearance/content-theme/content-type'] = array(
    'title' => 'Content type',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('content_theme_admin_content_type'),
    'access arguments' => array('administer themes'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'file' => 'content_theme.admin.inc',
  );
  $items['admin/appearance/content-theme/content-node'] = array(
    'title' => 'Content node',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('content_theme_admin_content_node'),
    'access arguments' => array('administer themes'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'content_theme.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_custom_theme().
 */
function content_theme_custom_theme() {

  $arg = arg();

  if ($arg[0] == 'node' && (is_numeric($arg[1]) || ($arg[1] == 'add' && !is_null($arg[2])))) {

    if ($arg[1] == 'add') {
      $theme_node = FALSE;
      $theme_type = config_get('node.type.' . strtr($arg[2], array('-' => '_')), 'settings.content_theme_edit');
      $theme_wide = config_get('content_theme.content_wide', 'content_theme_edit');
    }
    elseif (isset($arg[2]) && $arg[2] == 'edit') {
      $type_name = db_query('SELECT type FROM {node} WHERE nid = :nid', array(':nid' => $arg[1]))->fetchField();

      $theme_node = db_query('SELECT theme FROM {content_theme_node} WHERE nid = :nid AND action = :action', array(':nid' => $arg[1], ':action' => 'edit'))->fetchField();
      $theme_type = config_get('node.type.' . $type_name, 'settings.content_theme_edit');
      $theme_wide = config_get('content_theme.content_wide', 'content_theme_edit');
    }
    else {
      $type_name = db_query('SELECT type FROM {node} WHERE nid = :nid', array(':nid' => $arg[1]))->fetchField();

      $theme_node = db_query('SELECT theme FROM {content_theme_node} WHERE nid = :nid AND action = :action', array(':nid' => $arg[1], ':action' => 'view'))->fetchField();
      $theme_type = config_get('node.type.' . $type_name, 'settings.content_theme_view');
      $theme_wide = config_get('content_theme.content_wide', 'content_theme_view');
    }

    if ($theme_node !== FALSE && $theme_node != '-content_wide-') {
      $custom_theme = $theme_node;
    }
    else {
      if ($theme_type != '-content_wide-' && !$theme_node) {
        $custom_theme = $theme_type;
      }
      else {
        $custom_theme = $theme_wide;
      }
    }

    return $custom_theme;
  }
}


/**
 * Implements hook_config_info().
 */
function content_theme_config_info() {

  $prefixes['content_theme.content_wide'] = array(
    'label' => t('Content wide settings'),
    'group' => t('Content theme'),
  );

  return $prefixes;
}


/**
 * Implements hook_node_type_load().
 */
function content_theme_node_type_load(&$types) {

  foreach ($types as $type_name => $type) {

    $types[$type_name]->settings += array(
      'content_theme_edit' => '-content_wide-',
      'content_theme_view' => '-content_wide-',
    );
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Configure content type themes.
 */
function content_theme_form_node_type_form_alter(&$form, $form_state) {
  $node_type = $form['#node_type'];

  if (isset($form['type'])) {

    $form['content_theme'] = array(
      '#type' => 'fieldset',
      '#title' => t('Content theme settings'),
      '#description' => t('Applies to all content based on this content type and overrides content wide themes and the system default. But these settings can be overridden by content node settings.'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
      '#attributes' => array(
        'class' => array('content-theme-settings-form'),
      ),
      '#attached' => array(
        'js' => array(backdrop_get_path('module', 'content_theme') . '/scripts/content_theme.admin.js'),
      ),
      '#access' => user_access('administer themes'),
      '#weight' => 40,
    );
    $form['content_theme']['content_theme_edit'] = array(
      '#type' => 'select',
      '#title' => t('Creating & editing theme'),
      '#description' => t('Choose which theme the content creating and editing pages should display in. Default theme: %default_theme.', array('%default_theme' => t('Content wide theme'))),
      '#default_value' => $node_type->settings['content_theme_edit'],
      '#options' => content_theme_get_themes_options_content_type(),
    );
    $form['content_theme']['content_theme_view'] = array(
      '#type' => 'select',
      '#title' => t('Viewing theme'),
      '#description' => t('Choose which theme the content viewing pages should display in. Default theme: %default_theme.', array('%default_theme' => t('Content wide theme'))),
      '#default_value' => $node_type->settings['content_theme_view'],
      '#options' => content_theme_get_themes_options_content_type(),
    );
  }
}


/**
 * Implements hook_node_load().
 */
function content_theme_node_load($nodes, $types) {

  foreach ($nodes as $nid => $node) {

    $theme = db_query('SELECT theme FROM {content_theme_node} WHERE nid = :nid AND action = :action', array(':nid' => $node->nid, ':action' => 'edit'))->fetchField();
    $nodes[$nid]->content_theme_edit = $theme !== FALSE ? $theme : '-content_type-';

    $theme = db_query('SELECT theme FROM {content_theme_node} WHERE nid = :nid AND action = :action', array(':nid' => $node->nid, ':action' => 'view'))->fetchField();
    $nodes[$nid]->content_theme_view = $theme !== FALSE ? $theme : '-content_type-';
  }
}


/**
 * Implements hook_node_insert().
 */
function content_theme_node_insert(Node $node) {

  if ($node->content_theme_edit != '-content_type-') {
    db_insert('content_theme_node')
      ->fields(array('nid' => $node->nid, 'action' => 'edit', 'theme' => $node->content_theme_edit))
      ->execute();
  }

  if ($node->content_theme_view != '-content_type-') {
    db_insert('content_theme_node')
      ->fields(array('nid' => $node->nid, 'action' => 'view', 'theme' => $node->content_theme_view))
      ->execute();
  }
}


/**
 * Implements hook_node_update().
 */
function content_theme_node_update(Node $node) {

  content_theme_node_delete($node);
  content_theme_node_insert($node);
}


/**
 * Implements hook_node_delete().
 */
function content_theme_node_delete(Node $node) {

  db_delete('content_theme_node')
    ->condition('nid', $node->nid)
    ->execute();
}


/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Configure content node themes.
 */
function content_theme_form_node_form_alter(&$form, $form_state) {
  $node = $form['#node'];

  $form['content_theme'] = array(
    '#type' => 'fieldset',
    '#title' => t('Content theme settings'),
    '#description' => t('Applies only to this content node and overrides the content type themes, content wide themes, and the system default.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#group' => 'additional_settings',
    '#attributes' => array(
      'class' => array('content-theme-settings-form'),
    ),
    '#attached' => array(
      'js' => array(backdrop_get_path('module', 'content_theme') . '/scripts/content_theme.js'),
    ),
    '#access' => user_access('select '. $node->type .' content editing theme') || user_access('select '. $node->type .' content viewing theme'),
    '#weight' => 40,
  );
  $form['content_theme']['content_theme_edit'] = array(
    '#type' => 'select',
    '#title' => t('Editing theme'),
    '#description' => t('Choose which theme the content creating and editing pages should display in.'),
    '#default_value' => isset($node->content_theme_edit) ? $node->content_theme_edit : '-content_type-',
    '#options' => content_theme_get_themes_options_content_node(),
    '#access' => user_access('select '. $node->type .' content editing theme'),
  );
  $form['content_theme']['content_theme_view'] = array(
    '#type' => 'select',
    '#title' => t('Viewing theme'),
    '#description' => t('Choose which theme the content viewing pages should display in.'),
    '#default_value' => isset($node->content_theme_view) ? $node->content_theme_view : '-content_type-',
    '#options' => content_theme_get_themes_options_content_node(),
    '#access' => user_access('select '. $node->type .' content viewing theme'),
  );
}


/**
 * Helper functions.
 */
function content_theme_get_themes() {

  static $themes = array();

  if (!$themes) {

    $result = db_query('SELECT name, status, info FROM {system} WHERE type = :type', array(':type' => 'theme'));
    foreach ($result as $theme) {
      $theme->info = unserialize($theme->info);

      if (empty($theme->info['hidden']) || !$theme->info['hidden']) {
        $themes[$theme->name] = array(
          'name' => $theme->name,
          'label' => $theme->info['name'],
          'status' => $theme->status,
        );
      }
    }
  }

  return $themes;
}

function content_theme_get_themes_list() {

  static $themes = array();

  if (!$themes) {

    foreach (content_theme_get_themes() as $theme) {
      $themes[$theme['name']] = $theme['label'];
    }

    asort($themes, SORT_NATURAL | SORT_FLAG_CASE);
  }

  return $themes;
}

function content_theme_get_themes_options_content_wide() {

  $options['0'] = '<'. t('System default theme') .'>';
  $options += content_theme_get_themes_list();

  return $options;
}

function content_theme_get_themes_options_content_type() {

  $options['0'] = '<'. t('System default theme') .'>';
  $options['-content_wide-'] = '<'. t('Content wide theme') .'>';
  $options += content_theme_get_themes_list();

  return $options;
}

function content_theme_get_themes_options_content_node() {

  $options['0'] = '<'. t('System default theme') .'>';
  $options['-content_wide-'] = '<'. t('Content wide theme') .'>';
  $options['-content_type-'] = '<'. t('Content type theme') .'>';
  $options += content_theme_get_themes_list();

  return $options;
}

function content_theme_get_theme_label($theme, $expand = FALSE) {

  static $themes = array();

  if (!$themes) {

    $themes['0'] = array('label' => t('System default theme'), 'status' => 1);
    $themes['-content_wide-'] = array('label' => t('Content wide theme'), 'status' => 1);
    $themes['-content_type-'] = array('label' => t('Content type theme'), 'status' => 1);
    $themes += content_theme_get_themes();
  }

  if (isset($themes[$theme])) {
    $name = $expand && !$themes[$theme]['status'] ? check_plain($themes[$theme]['label']) . '<br><small>' . t('(Disabled)') . '</small>' : $themes[$theme]['label'];
  }
  else {
    $name = $expand ? $theme . '<br><small>' . t('(Not available)') . '</small>' : $theme;
  }

  return $name;
}

function content_theme_get_theme_label_placeholder($theme, $placeholder = FALSE) {

  if ($placeholder || $theme === '0' || $theme === '-content_wide-' || $theme === '-content_type-') {
    $label = backdrop_placeholder(content_theme_get_theme_label($theme));
  }
  else {
    $label = content_theme_get_theme_label($theme);
  }

  return $label;
}
